In [1]:
%%capture

import os
import pandas as pd

from transformers import *
from corpus_helper import CorpusStreamer

init_config()

In [2]:
teststring = "This is a test with three sentences. Indices should be reset here. Sarah is not home."

In [ ]:
author = "chesterton"
s = CorpusStreamer("../DataAcquisition/data/{}".format(author)).toString()

In [3]:
%%time
features = apply_pipeline(teststring, TextParser(), 10**6)
encoded = FeatureEncoder().fit_transform(features)

c:\users\kevin\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


ValueError: negative dimensions are not allowed

In [6]:
f = [features]*3

In [7]:
import numpy as np

In [61]:
np.concatenate([np.ones(l)*i for i,l in enumerate(map(len, f))])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2.])

In [12]:
f3 = pd.concat(f, ignore_index=True)

In [13]:
f3["y"] = labels

In [16]:
enc = FeatureEncoder().fit_transform(f3)

c:\users\kevin\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [32]:
features.shape

(19, 5)

In [53]:
fm = features.as_matrix()
patches = extract_patches(fm, (10, fm.shape[1]), 5)

c:\users\kevin\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [56]:
patches.shape

(2, 1, 10, 5)

In [60]:
np.rollaxis(patches, 1, 4).shape

(2, 10, 5, 1)

In [69]:
extract_patches(labels, 10, 5)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

array([0., 0., 0., 1., 1., 1., 1., 2., 2., 2.])